# Generated by Django 4.1.4 on 2022-12-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fav',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
