# Generated by Django 4.1.4 on 2022-12-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fav',
            new_name='favourite',
        ),
    ]
